config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts do
    collection do
      get :top_rated
      get :recent
      get :trending
      get :filter_search
    end
    member do
      resources :feedbacks
    end
  end

  resources :chatrooms do
    resources :messages
  end

  resources :listposts

  resources :lists

  # resources :chatrooms, only: :show do
  #   resources :messages, only: :create
  # end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :listposts, dependent: :destroy
  has_many :posts, through: :listposts, dependent: :destroy

  validates_presence_of :name

  include PgSearch::Model
  pg_search_scope :search_by_name, against: [:name], using: { tsearch: { prefix: true } }

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, only: %i[ show edit update destroy]
  def index
    @lists = List.where(user_id: current_user)
    @list = List.new
  end

  def show
    # @post = Post.where(list_id: @list.id)
    @listpost = Listpost.new
    if params[:query].present?
      @searched_posts = Post.search_by_title_and_body(params[:query]).limit(5)
    else
      @searched_posts = Post.all.order(:created_at).limit(5)
    end
    respond_to do |format|
      format.html
      format.text { render partial: "lists/posts", locals: {searched_posts: @searched_posts}, formats: [:html] }
    end
  end

  def new
    if user_signed_in?
      @list = List.new
    else
      redirect_to new_user_session_path, danger: "login to create to list"
    end
  end

  def create
    if user_signed_in?
      @list = List.new(list_params)
      @list.user = current_user
      if @list.save
        redirect_to list_path(@list), success: "Created your list #{@list.name}"
      else
        render :new, status: :unprocessable_entity
      end
    else
      redirect_to new_user_session_path, danger: "login to create to list"
    end
  end

  def edit
  end

  def update
    @list.update(list_params)
    if @list.user == current_user && @list.save
      redirect_to lists_path, success: "Your list has been updated"
    end
  end

  def destroy
    if @list.user == current_user
      @list.destroy
      redirect_to lists_path, status: :see_other
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end

end

app/views/lists/_added_posts.html.erb
<%# <div data-add-post-to-list-target="posts"> %>
<%# </div> %>
    <%= link_to post_path(listpost.post), class: "" do %>
      <div class="slim-card">
            <i class="fa-solid fa-bookmark clickable-coral favourite-icon"></i>

        <% if listpost.post.photo.present? %>
          <%= cl_image_tag listpost.post.photo.key, class: "card-media" %>
          <% else %>
          <%= image_tag "https://s15.postimg.cc/temvv7u4r/recipe.jpg" %>
        <% end %>
          <h2 class="card-title"><%= listpost.post.title %></h2>
      </div>
    <% end %>

app/views/lists/_list_index.html.erb
<div class="container d-none show-dropdown list-dropdown position-absolute" data-post-dropdown-target="listDropdown">
  <div class="d-flex align-items-center">
  <i class="fa-solid fa-list-ul me-2 primary-green"></i>

  <span class="text-grey">Add to a list</span>
  </div>
  <div class="list-list">
    <div class="search-lists background-orange p-2 rounded" data-controller="search-lists">
      <% if @searched_lists.nil? %>
          <%= link_to 'Create new List', lists_path %>
        <% else %>
          <%= form_with url: post_path, method: :get, html: {class: "d-flex", data: {search_lists_target: "form searchbar"}} do |f| %>
          <i class="fa-solid fa-magnifying-glass search background-white"></i>
            <%= f.text_field :query,
                value: params[:query],
                class: "form-control",
                placeholder: "Find a list",
                data: {
                  search_lists_target: "input",
                  action: "keyup->search-lists#update click->search-lists#show",
                } %>
          <% end %>
            <%= render "posts/my_lists", searched_lists: @searched_lists %>
        <% end %>
      <%= link_to lists_path do %>
      <div class="pt-2 border-top">
        <div class="new-list">
          <i class="fa-solid fa-plus me-2"></i>
          <span>Create a new list</span>
          </div>
          </div>
      <% end %>
    </div>

    </div>





</div>

app/views/lists/_my_posts.html.erb
<div class="search-results" data-search-posts-target="list">
  <% @searched_posts.each do |post| %>
    <div class="search-post-results">
      <div class="post-title">
        <p><%= post.title %></p>
      </div>
      <div class="post-add-button">
        <%= simple_form_for([@listpost]) do |f| %>
          <%= f.hidden_field :post_id, value: post.id %>
          <%= f.hidden_field :list_id, value: @list.id %>
          <%= f.submit 'Add', class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/_posts.html.erb
<div class="search-results py-3" data-search-posts-target="list">
  <div class="headline-missing">
    <% if params[:query].nil? %>
      <h4>Recommended Posts:</h4>
    <% end %>
  </div>
  <% searched_posts.each do |post| %>
    <div class="search-post-results" data-add-post-to-list-target="results">
      <div class="results-grid">
        <div class="list-post-card">
          <%= cl_image_tag post.photo.key, class: "" %>
          <div class="post-details">
            <%= link_to post_path(post)do %>
              <h4><%= post.title %></h4>
              <p>By: <%= post.user.username %></p>
              <% end %>
          </div>
            <div class="post-add-button">
              <%= simple_form_for([@listpost],
                data: {add_post_to_list_target: "form",
                      add_post_to_list_id_param: "#{post.id}",
                      action: "submit->add-post-to-list#send"}) do |f| %>
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.hidden_field :list_id, value: @list.id %>
                <%= f.submit '+', class: "fa-solid toggle-button" %>
                      <% end %>
            </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/lists/edit.html.erb
<div class="container">
  <h1>Edit your list</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name, placeholder: "Enter your tasklist name"%>
    <%= f.submit class: "main-btn my-4 " %>
  <% end %>
</div>

app/views/lists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12 mt-3 background-orange rounded px-4 pb-4">
    <div class="d-flex align-items-center">
        <i class="fa-solid fa-list-ul background-white pe-3"></i>
        <h2 class="my-5 background-white m-0">My lists</h2>
      </div>
      <ul>
        <% @lists.each do |list| %>
          <%= link_to list_path(list) do %>
            <div class="list-card position-relative">
              <div class="left-list">
                <i class="fa-solid fa-list-ul clickable-coral"></i>
                <h3 class="mb-4"><%= list.name %></h3>
                  <%= pluralize(list.posts.count, 'post')%>
                <%# <p><%= link_to "Edit list", edit_list_path(list) %>
              </div>
              <div class="position-absolute list-card-date">
                <p>Created: <%= list.created_at.strftime("%d %B")%></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </ul>
    </div>

    <div class=" col-lg-6 col-md-6 col-sm-12 px-5 mt-3">
      <h2 class="my-5">Create a new list</h2>
      <%= simple_form_for @list do |f| %>
        <%= f.input :name, placeholder: "Enter your list name"%>
        <%= f.submit 'Create list', class: "main-btn mx-auto mt-5" %>
      <% end %>
    </div>


  </div>
</div>

app/views/lists/show.html.erb
<div class="background-orange">
<div class="container pt-3">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-6 col-sm-12 b-background-white mb-5" data-controller="add-post-to-list" data-add-post-to-list-position-value="afterbegin">
      <div class="d-flex align-items-center justify-content-between pb-3 border-bottom">
        <div class="bookmark-details d-flex align-items-center">
          <i class="fa-solid fa-bookmark pe-3 text-grey"></i>
          <h1 class="text-grey"><%= @list.name %></h1>
        </div>
        <div class="edit-delete-list d-flex">
          <div class="edit-list px-2">
            <div class="icon-btn">
              <%= link_to edit_list_path(@list) do %>
                <i class="fa-solid fa-pen-to-square"></i>
                <% end %>
          </div>
          </div>
          <div class="icon-btn">
          <%= link_to list_path(@list) do %>
            <i class="fa-solid fa-trash"></i>
            <% link_to data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?"} %>
          <% end %>
          </div>
        </div>
      </div>
      <div class="top-of-list pt-3">
        <div class="listposts">
          <div class="listposts-container" data-add-post-to-list-target="posts">
            <% @list.listposts.each do |listpost| %>
              <%= render "lists/added_posts", listpost: listpost %>
            <% end %>
          </div>
        </div>
</div>
        <div class="search-posts" data-controller="search-posts">
          <div class="search-post-container mt-5">
            <h3 class="text-grey">Add to List </h3>
            <%= form_with url: list_path, method: :get, html: {class: "d-flex", data: {search_posts_target: "form"}} do |f| %>
                <%= f.text_field :query,
                        value: params[:query],
                        class: "form-control",
                        placeholder: "Search posts",
                        data: {
                          search_posts_target: "input",
                          action:"keyup->search-posts#update"
                        } %>
            <% end %>
            <%= render "lists/posts", searched_posts: @searched_posts, listpost: @listpost %>
          </div>
        </div>
      </div>


  </div>

  </div>
</div>