config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts do
    collection do
      get :top_rated
      get :recent
      get :trending
      get :filter_search
    end
    member do
      resources :feedbacks
    end
  end

  resources :chatrooms do
    resources :messages
  end

  resources :listposts

  resources :lists

  # resources :chatrooms, only: :show do
  #   resources :messages, only: :create
  # end
end

app/views/shared/_banner_search.html.erb
<div class="py-5 text-center container-fluid banner-search">
  <div class="row py-lg-5">
  <div class="col-lg-8 col-md-8 mx-auto p-3">
    <h1 class="lead mute-text">Shed the cost of living: </h1>
    <h1 class="lead mute-text">join the Sheddy community and</h1>
    <h1 class="lead mute-text">Do It Yourself</h1>
      <p><%= form_with url: posts_path, method: :get, class: "d-flex justify-content-center search-field" do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search for a post" %>
        <%= button_tag type: 'submit', class: "btn search-button", id: "register-button" do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      <% end %></p>
    </div>

  </div>

</div>
<%= render "shared/navbar" %>

app/views/shared/_footer.html.erb
<div class="background-green footer p-5 mt-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-4 col-12 order-1 logo">
        <%= image_tag "sheddy-logo" %>
      </div>
      <div class="col-12 col-lg-5 col-md-5  order-md-2 order-3 sign-up">
        <div class="d-flex align-items-center sign-up-text">
          <i class="fa-regular fa-envelope me-2"></i>
          <span>Sheddy inspiration straight to your inbox</span>
        </div>
        <p><%= form_with url: posts_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
          params[:email],
          class: "form-control",
          placeholder: "joe@joebloggs.com"
          %>
          <%= submit_tag "sign-up", class: "btn search-button" %>
        <% end %></p>
      </div>
      <div class="order-md-3 order-2 col-12 col-md-3 col-lg-3">
      <div class="d-flex social-icons flex-row-reverse">
        <i class="fa-brands fa-facebook"></i>
        <i class="fa-brands fa-instagram"></i>
        <i class="fa-brands fa-twitter"></i>
        <i class="fa-brands fa-tiktok"></i>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="b-background-white shadow-sm">
  <div class="container-fluid">
    <div class="row d-flex align-items-center">
      <div class="col-lg-2 col-md-2 col-9 order-1">
        <%= link_to root_path do  %>
          <%= image_tag("sheddy-advice-logo.svg") %>
        <% end %>
      </div>
      <div class="collections col-lg-9 col-md-9 col-sm-4 order-3 order-md-3">
        <ul class="nav d-flex justify-content-around">
            <%= link_to filter_search_posts_path(category: 'House Maintanance') do  %>
              <li class="d-flex align-items-center">
                <i class="fa-solid fa-house p-2"></i>
              <h2>House maintenance</h2></li>
            <% end %>
              <%= link_to filter_search_posts_path(category: 'In the Bathroom') do %>
              <li class="d-flex align-items-center">
                <i class="fa-solid fa-sink p-2"></i>
                <h2>In the bathroom</h2>
              </li>
            <% end %>
            <%= link_to filter_search_posts_path(category: 'In the Kitchen') do %>
              <li class="d-flex align-items-center">
              <i class="fa-solid fa-kitchen-set p-2"></i>
              <h2>In the kitchen</h2></li>
            <% end %>
            <%= link_to filter_search_posts_path(category: 'In the Garden') do %>
              <li class="d-flex align-items-center">
              <i class="fa-solid fa-worm p-2"></i>
              <h2>In the garden</h2></li>
            <% end %>
        </ul>
      </div>
      <div class="col-lg-1 col-md-1 col-2 offset-1 offset-md-0 offset-lg-0 d-flex align-items-right order-2 order-md-3">
      <div class="nav-item dropdown" data-controller="menu-dropdown">
              <%= content_tag :div, class: " dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false do %>
            <%= content_tag :div, class:"nav-icon3",  data: {menu_dropdown_target: "hamburger", action: "click->menu-dropdown#reveal"}  do %>
                <%= content_tag :span %>
                <%= content_tag :span %>
                <%= content_tag :span %>
                <%= content_tag :span %>
              <% end %>
                          <% end %>

              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <ul class="nav-items p-2">
                  <% if user_signed_in? %>
                  <div class="background-green mb-2 ps-2 d-flex align-items-center">
                    <li><i class="fa-solid fa-user background-white px-3 py-3"></i><span class="background-white">Hello, <%= current_user.username %></span></li>
                  </div>
                  <li><i class="fa-solid fa-graduation-cap ps-4"></i><%= link_to "Posts", posts_path, class: "dropdown-item" %></li>
                  <li><i class="fa-solid fa-circle-plus ps-4"></i><%= link_to "Add Post", new_post_path, class: "dropdown-item" %></li>
                  <li><i class="fa-solid fa-list-ul ps-4"></i><%= link_to "Lists", lists_path, class: "dropdown-item" %></li>
                  <li><i class="fa-solid fa-message ps-4"></i></i><%= link_to "Messages", chatrooms_path, class: "dropdown-item" %></li>
                  <li><i class="fa-solid fa-right-from-bracket ps-4"></i><%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %></li>
                  <% else %>
                  <li><i class="fa-solid fa-right-to-bracket ps-4"></i><%= link_to "Log-in", new_user_session_path, class: "dropdown-item" %></li>
                  <li><i class="fa-solid fa-user-plus ps-4"></i><%= link_to "Sign-up", new_user_registration_path, class: "dropdown-item" %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
    </div>
  </div>
</div>

app/views/shared/_pop_up.html.erb
<div class="container">
  <div class="row">
    <div id='main' class="col-md-8 col-md-offset-2">
      <% flash.each do |name, message| %>
        <div class= "alert alert-<%=name %> alert-dismissible show" role="alert">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_short_banner_search.html.erb
<div class="py-1 text-center container-fluid banner-search">
  <div class="row py-lg-1">
  <div class="col-lg-6 col-md-8 mx-auto">

      <p><%= form_with url: posts_path, method: :get, class: "d-flex justify-content-center search-field" do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search for a post"
        %>
        <%= button_tag type: 'submit', class: "btn search-button", id: "register-button" do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      <% end %></p>
    </div>

  </div>

</div>
<%= render "shared/navbar" %>

app/views/shared/_user_card.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-8">
      <div class="user-card-body d-flex align-items-center">
        <div class="row">
          <div class="col-12 col-md-4 m-auto">
            <div class="d-flex justify-content-center">
              <% if @post.user.photo.present? %>
                <%= cl_image_tag @post.user.photo.key, class: "avatar-bordered", alt: "avatar-bordered" %>
              <% else %>
                <%= image_tag 'Meeseeks.png', class: "avatar-bordered-new", alt: "avatar-bordered" %>
              <% end %>
            </div>
          </div>
          <div class="col-12 col-md-4 m-auto py-4">
            <div class="d-flex justify-content-center">
            <i class="fa-solid fa-user pe-2"></i>
            <span><%= @post.user.username %></span>
            </div>
          </div>
          <div class="col-12 col-md-4">
            <div class="button-list">
              <% if user_signed_in? %>
                <% if current_user.id == @post.user.id %>
                  <%= link_to 'See your messages', chatrooms_path, class: "main-btn" %>
                <% elsif @existingchatroom.present? %>
                  <%= link_to 'Send message', chatroom_path(@existingchatroom), class: "main-btn" %>
                  <div class="main-btn" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                      Leave a review
                  </div>
                <% else %>
                  <%= simple_form_for(@newchatroom) do |f| %>
                    <% if user_signed_in? %>
                      <%= f.hidden_field :sender_id, value: current_user.id %>
                    <% end %>
                      <%= f.hidden_field :receiver_id, value: @post.user.id %>
                      <%= f.submit 'Send message', class: "main-btn" %>
                  <% end %>
                  <div class="main-btn" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                      Leave a review
                  </div>
                <% end %>
              <% else %>
                <%= link_to 'Send message', new_user_session_path, class: "main-btn" %>
                <%= link_to 'Leave a review', new_user_session_path, class: "main-btn" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>