config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts do
    collection do
      get :top_rated
      get :recent
      get :trending
      get :filter_search
    end
    member do
      resources :feedbacks
    end
  end

  resources :chatrooms do
    resources :messages
  end

  resources :listposts

  resources :lists

  # resources :chatrooms, only: :show do
  #   resources :messages, only: :create
  # end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable

  belongs_to :user

  has_many :feedbacks, dependent: :destroy
  has_many :listposts, dependent: :destroy
  has_many :lists, through: :listposts, dependent: :destroy
  # has_many :listposts
  validates :title, presence: true
  # validates :title, uniqueness: true
  validates :body, length: { minimum: 20 }
  validates_presence_of :user
  validates_presence_of :category
  has_one_attached :photo
  has_one_attached :video
  include PgSearch::Model
  pg_search_scope :search_by_title_and_body,
    against: [ :title, :body ],
    using: {
      tsearch: { prefix: true }
    }

  def self.top_rated
    @post = Post.joins(:feedbacks).group("posts.id").order("avg(feedbacks.rating) desc").first(10)
  end

  def self.recent
    @posts = Post.last(8)
  end

  def self.trending
    @posts = Post.offset(rand(Post.count)).first(8)
  end
end

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sheddyadvice - Shed the cost of living with us!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= favicon_link_tag 'spanner.svg' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/banner_search" %>
    <div class="container p-5 home-intro-section">
      <div class="nuts" data-controller="nuts-rotate" data-action="scroll@window->nuts-rotate#rotate">
        <%= image_tag 'nut.svg' , data: {nuts_rotate_target:"nutOne"} %>
        <%= image_tag 'nut.svg', data: {nuts_rotate_target:"nutTwo"}  %>
        <%= image_tag 'nut.svg', data: {nuts_rotate_target:"nutThree"}  %>
      </div>
      <div class="intro-text pt-3 text-grey">
        <h2>Join our community:</h2>
      </div>
      <div class="button-container d-flex justify-content-center p-5">
        <%= link_to posts_path, class: "main-btn"  do %>
          <%= icon("fa-solid", "magnifying-glass") %>
          <span class="mx-2">Explore tutorials</span>
        <% end %>
        <%=  link_to new_post_url, class: "main-btn"  do %>
          <%= icon("fa-solid", "graduation-cap") %>
          <span class="mx-2">Share expertise</span>
        <% end %>
      </div>
    </div>

    <div class="orange-background p-md-5 p-3">
        <div class="paintbrush">
          <h2 class="headline pt-5 background-white">Top Rated</h2>
            <div class="scroll-box d-flex">
                  <% @top_rated_posts = Post.top_rated %>
                  <% @top_rated_posts.each do |post| %>
                    <%= link_to post_path(post) do %>
                      <div class="home-card mb-3">
                        <% if post.photo.present?  %>
                          <%= cl_image_tag post.photo.key , html: { crop: :fill} %>
                        <% else %>
                          <%= image_tag "https://s15.postimg.cc/temvv7u4r/recipe.jpg", html: { crop: :fill}  %>
                        <% end %>
                        <h2 class="card-title"><%= post.title %></h2>
                        <div class="card-details">
                          <span class="card-author">created by: <%= User.find(post.user_id).username %></span>
                          <% feedback_rating = Feedback.average_rating(post) %>
                          <% if post.feedback_ids.present? %>
                            <% if feedback_rating % 1 == 0 %>
                              <span class="card-rating">Rating: <% feedback_rating.to_i.times do %>
                              <i class="fa-solid fa-star primary-green"></i>
                              <% end %>
                              </span>
                            <% else %>
                              <span class="card-rating"> Rating: <% feedback_rating.to_i.times do %>
                              <i class="fa-solid fa-star primary-green"></i>
                              <% end %>
                              <i class="fa-solid fa-star-half primary-green"></i>
                              </span>
                              <% end %>
                          <% else %>
                            <span class="card-rating">Rating: Not Rated yet</span>
                          <% end %>

                        </div>

                    </div>
                    <% end %>
                <% end %>
        </div>
      </div>
    </div>
    <%# Next section %>
    <div class="b-background-white p-md-5 p-3">
        <div class="spanner">
          <h2 class="headline pt-5 primary-green">Trending</h2>
            <div class="scroll-box d-flex">
                <% @trending_posts = Post.trending %>
                <% @trending_posts.each do |post| %>
                  <%= link_to post_path(post) do %>
                    <div class="home-card mb-3">
                      <% if post.photo.present?  %>
                        <%= cl_image_tag post.photo.key,  html: { crop: :fill} %>
                      <% else %>
                        <%= image_tag "https://s15.postimg.cc/temvv7u4r/recipe.jpg", html: { crop: :fill}  %>
                      <% end %>
                      <h2 class="card-title"><%= post.title %></h2>
                       <div class="card-details">
                          <span class="card-author">created by: <%= User.find(post.user_id).username %></span>
                          <% feedback_rating = Feedback.average_rating(post) %>
                          <% if post.feedback_ids.present? %>
                            <% if feedback_rating % 1 == 0 %>
                              <span class="card-rating">Rating: <% feedback_rating.to_i.times do %>
                              <i class="fa-solid fa-star primary-green"></i>
                              <% end %>
                              </span>
                            <% else %>
                              <span class="card-rating"> Rating: <% feedback_rating.to_i.times do %>
                              <i class="fa-solid fa-star primary-green"></i>
                              <% end %>
                              <i class="fa-solid fa-star-half primary-green"></i>
                              </span>
                              <% end %>
                          <% else %>
                            <span class="card-rating">Rating: Not Rated yet</span>
                          <% end %>

                        </div>

                    </div>
                    <% end %>
                  <% end %>

                  </div>
              </div>
            </div>


    <%# next section %>
    <div class="orange-background p-md-5 p-3">
        <div class="hammer">
          <h2 class="headline pt-5 background-white">Recent Posts</h2>
            <div class="scroll-box d-flex">
                <% @recent_posts = Post.trending %>
                <% @recent_posts.each do |post| %>
                  <%= link_to post_path(post) do %>
                    <div class="home-card mb-3">
                    <% if post.photo.present?  %>
                      <%= cl_image_tag post.photo.key,  html: { crop: :fill} %>
                    <% else %>
                      <%= image_tag "https://s15.postimg.cc/temvv7u4r/recipe.jpg", html: { crop: :fill}  %>
                    <% end %>
                    <h2 class="card-title"><%= post.title %></h2>
                    <div class="card-details">
                      <span class="card-author">created by: <%= User.find(post.user_id).username %></span>
                      <% feedback_rating = Feedback.average_rating(post) %>
                      <% if post.feedback_ids.present? %>
                        <% if feedback_rating % 1 == 0 %>
                          <span class="card-rating">Rating: <% feedback_rating.to_i.times do %>
                            <i class="fa-solid fa-star primary-green"></i>
                         <% end %>
                          </span>
                      <% else %>
                        <span class="card-rating"> Rating: <% feedback_rating.to_i.times do %>
                          <i class="fa-solid fa-star primary-green"></i>
                      <% end %>
                      <i class="fa-solid fa-star-half primary-green"></i>
                      </span>
                             <% end %>
                          <% else %>
                            <span class="card-rating">Rating: Not Rated yet</span>
                          <% end %>

                        </div>

                    </div>
                  <% end %>
                  <% end %>

                  </div>
              </div>
            </div>

    <%= render "shared/footer" %>
  </body>
</html>