config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts do
    collection do
      get :top_rated
      get :recent
      get :trending
      get :filter_search
    end
    member do
      resources :feedbacks
    end
  end

  resources :chatrooms do
    resources :messages
  end

  resources :listposts

  resources :lists

  # resources :chatrooms, only: :show do
  #   resources :messages, only: :create
  # end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  scope :top, -> { select('post_id, average(rating) as average').group(:post_id).order('average DESC').limit(3) }
  belongs_to :user
  belongs_to :post
  validates_presence_of :rating, :user_id, :post_id

  def self.average_rating(post)
    feedbacks = post.feedbacks
    feedbacks_sum = feedbacks.to_a.map(&:rating).sum
    feedbacks_count = feedbacks.count
    return feedbacks_sum / feedbacks_count.to_f
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  def new
  end

  def create
    if user_signed_in?
      @post = Post.find(params[:id])
      @feedback = Feedback.new(feedback_params)
      @feedback.post = @post
      @feedback.user = current_user
      respond_to do | format |
      if @feedback.save
          format.html { redirect_to post_path(@post) }
          format.json
        else
          format.html { render "posts/show", status: :unprocessable_entity }
          format.json
      end
      end
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @feedback = Feedback.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @feedback = Feedback.find(params[:id])
    @feedback.update(feedback_params)
    @feedback.user = current_user
    @feedback.post = @post
    if @feedback.save
      redirect_to post_path, success: "Successfully updated"
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:rating, :comment, :post_id, :user_id)
  end

end

app/views/feedbacks/_feedback.html.erb
<div class="review">
  <div class="review-card">
    <div class="avatar-circle">

      <% if feedback.user.photo.present? %>
        <%= cl_image_tag feedback.user.photo.key, class: "avatar-small-circle", alt: "avatar-bordered" %>
      <% else %>
        <%= image_tag 'Meeseeks.png', class: "avatar-small-circle", alt: "avatar-bordered" %>
      <% end %>
    </div>
    <div class="review-body">
      <div class="review-username">
        <h4><b><%= feedback.user.username %></b></h4>
      </div>
      <div class="review-rating">
        <p>Rating: <% feedback.rating.times do %>
          <i class="fa-solid fa-star primary-green"></i>
        <% end %></p>
      </div>
      <div class="review-comment">
        <% if feedback.comment.present? %>
          <div class="bottom-comment">
            <p><%= feedback.comment %></p>
          </div>
        <% end %>
      </div>

    </div>
    <div class="middle-review grouped">
    </div>
    <div class="right-review grouped">
      <p>on <%= feedback.created_at.strftime("%d %B")%></p>
    </div>
    <%# <%= link_to 'Edit', edit_post_feedback_path(post), class: "btn btn-primary"%>
  </div>

</div>

app/views/feedbacks/_form.html.erb
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Submit a Review</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="add-review">
          <%= simple_form_for([@feedback]) do |f| %>
              <%= f.input :rating, placeholder: "Enter a rating"%>
              <%= f.input :comment %>
              <%= f.submit 'Add Review', class: "main-btn" %>
            <% end %>
        </div>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<%# <%= simple_form_for([@feedback],
            data: {add_review_in_list_target: "form",
            action: "submit->add-review-in-list#send"
          }) %>

app/views/feedbacks/edit.html.erb
<div class="container">
  <h1>Edit Comment</h1>
  <%= link_to 'Back to Post', post_path(@post) %>
  <%= simple_form_for([@post, @feedback]) do |f| %>
        <%= f.input :rating, placeholder: "Enter a rating"%>
        <%= f.input :comment %>
        <%= f.submit class: "button-primary" %>
  <% end %>
</div>